export const categories = [
  { id: "traditional", label: "Traditional" },
  { id: "semi-traditional", label: "Semi Traditional" },
  { id: "semi-modern", label: "Semi Modern" },
  { id: "classic", label: "Classic" },
]

export const projects = [
  {
    id: 1,
    title: "Traditional",
    category: "traditional",
    images: [
      "/img/portfolio/casa6/4.jpg",
      "/img/portfolio/casa6/5.jpg",
      "/img/portfolio/casa6/1.jpg",
      "/img/portfolio/casa6/2.jpg",
      "/img/portfolio/casa6/3.jpg",
      "/img/portfolio/casa6/6.jpg",
      "/img/portfolio/casa6/7.jpg",
      "/img/portfolio/casa6/8.jpg",
      "/img/portfolio/casa6/9.jpg",
      "/img/portfolio/casa1/1.jpg",
      "/img/portfolio/casa1/2.jpg",
      "/img/portfolio/casa1/3.jpg",
      "/img/portfolio/casa1/4.jpg",
      "/img/portfolio/casa1/5.jpg",
      "/img/portfolio/casa1/6.jpg",
      "/img/portfolio/casa1/7.jpg",
      "/img/portfolio/casa1/8.jpg",
      "/img/portfolio/casa1/9.jpg",
      "/img/portfolio/casa1/10.jpg",
      "/img/portfolio/casa1/11.jpg",
      "/img/portfolio/casa1/12.jpg",
    ],
  },
  {
    id: 2,
    title: "Semi Traditional",
    category: "semi-traditional",
    images: [
      "/img/portfolio/casa2/3.jpg",
      "/img/portfolio/casa2/1.jpg",
      "/img/portfolio/casa2/2.jpg",
      "/img/portfolio/casa2/4.jpg",
      "/img/portfolio/casa2/5.jpg",
      "/img/portfolio/casa2/6.jpg",
      "/img/portfolio/casa2/7.jpg",
      "/img/portfolio/casa2/8.jpg",
       "/img/portfolio/casa2/9.jpg",
      "/img/portfolio/casa2/10.jpg",
      "/img/portfolio/casa2/11.jpg",
      "/img/portfolio/casa2/12.jpg",
      "/img/portfolio/casa2/13.jpg",
      "/img/portfolio/casa2/14.jpg",
      "/img/portfolio/casa2/15.jpg",
      "/img/portfolio/casa2/16.jpg",
      "/img/portfolio/casa4/1.jpg",
      "/img/portfolio/casa4/2.jpg",
      '/img/portfolio/casa4/3.jpg',
      '/img/portfolio/casa4/4.jpg',
      '/img/portfolio/casa4/5.jpg',
      '/img/portfolio/casa4/6.jpg',
      '/img/portfolio/casa4/7.jpg',
      '/img/portfolio/casa4/8.jpg',
      '/img/portfolio/casa4/9.jpg',
      '/img/portfolio/casa4/10.jpg',
      '/img/portfolio/casa4/11.jpg',
      '/img/portfolio/casa4/12.jpg'
    ],
  },
  {
    id: 3,
    title: "Semi Modern",
    category: "semi-modern",
    images: [
      "/img/portfolio/casa7/1.jpg",
      "/img/portfolio/casa7/2.jpg",
      "/img/portfolio/casa7/3.jpg",
      "/img/portfolio/casa7/4.jpg",
      "/img/portfolio/casa7/5.jpg",
      "/img/portfolio/casa7/6.jpg",
      "/img/portfolio/casa7/7.jpg",
      "/img/portfolio/casa7/8.jpg",
      "/img/portfolio/casa7/9.jpg",
      "/img/portfolio/casa7/10.jpg",
      "/img/portfolio/casa7/11.jpg",
      "/img/portfolio/casa3/1.jpg",
      "/img/portfolio/casa3/2.jpg",
      "/img/portfolio/casa3/3.jpg",
      "/img/portfolio/casa3/4.jpg",
      "/img/portfolio/casa3/5.jpg",
      "/img/portfolio/casa3/6.jpg",
      "/img/portfolio/casa3/7.jpg",
      "/img/portfolio/casa3/8.jpg",
      "/img/portfolio/casa3/9.jpg",
      "/img/portfolio/casa3/10.jpg",
      "/img/portfolio/casa3/11.jpg",
      "/img/portfolio/casa3/12.jpg",
      "/img/portfolio/casa3/13.jpg",
      "/img/portfolio/casa3/14.jpg",
    ],
  },
  {
    id: 4,
    title: "Classic",
    category: "classic",
    images: [
      "/img/portfolio/casa5/1.jpg",
      "/img/portfolio/casa5/2.jpg",
      "/img/portfolio/casa5/3.jpg",
      "/img/portfolio/casa5/4.jpg",
      "/img/portfolio/casa5/5.jpg",
      "/img/portfolio/casa5/6.jpg",
      "/img/portfolio/casa5/7.jpg",
      "/img/portfolio/casa5/8.jpg",
      "/img/portfolio/casa5/9.jpg",
      "/img/portfolio/casa5/10.jpg",
      "/img/portfolio/casa5/11.jpg",
      "/img/portfolio/casa5/12.jpg",
      "/img/portfolio/casa5/13.jpg",
      "/img/portfolio/casa5/14.jpg",
    ],
  },
]

export type Category = typeof categories[0]
export type Project = typeof projects[0]